### ISSUE TITLE
biodiversity metrics exercise

### ISSUE THREAD

**Issue by emchristensen** [skmorgane/biodiversity-course#14]
For this year, we'll just demonstrate metrics using taxonomic diversity, but in the future it would be interesting to go through phylogenetic and functional as well.  Start with a question: how does rodent exclusion affect diversity of plants?  and go through different ways to approach.

**Comment by skmorgane** [comment]
To add to this, I think having most of the metric/alpha beta gamma stuff be hands on as opposed to reading might be a better experience for them than reading about metrics. Myabe expand to a series of tutorials/discussions of their results and approaches that help them think about these things in a hands-on way.

**Comment by skmorgane** [comment]
Lauren Trotta offered to help develop a phylogenetic module for this exercise.

**Comment by skmorgane** [comment]
Issues #30 and #32 created to deal with this issue
